In [1]:
from lightfm import LightFM
from lightfm.datasets import fetch_movielens
from lightfm.evaluation import precision_at_k

# Load the MovieLens 100k dataset. Only five
# star ratings are treated as positive.
data = fetch_movielens()

# Instantiate and train the model
model = LightFM(loss='warp')
model.fit(data['train'], epochs=100, num_threads=2)

# Evaluate the trained model
test_precision = precision_at_k(model, data['test'], k=3)

In [2]:
test_precision.mean()

0.123718634

In [3]:
for key, value in data.items():
    print(key, type(value), value.shape)

item_features <class 'scipy.sparse.csr.csr_matrix'> (1682, 1682)
item_labels <class 'numpy.ndarray'> (1682,)
test <class 'scipy.sparse.coo.coo_matrix'> (943, 1682)
item_feature_labels <class 'numpy.ndarray'> (1682,)
train <class 'scipy.sparse.coo.coo_matrix'> (943, 1682)


In [4]:
print(data['item_labels'][:30])

['Toy Story (1995)' 'GoldenEye (1995)' 'Four Rooms (1995)'
 'Get Shorty (1995)' 'Copycat (1995)'
 'Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)'
 'Twelve Monkeys (1995)' 'Babe (1995)' 'Dead Man Walking (1995)'
 'Richard III (1995)' 'Seven (Se7en) (1995)' 'Usual Suspects, The (1995)'
 'Mighty Aphrodite (1995)' 'Postino, Il (1994)'
 "Mr. Holland's Opus (1995)" 'French Twist (Gazon maudit) (1995)'
 'From Dusk Till Dawn (1996)' 'White Balloon, The (1995)'
 "Antonia's Line (1995)" 'Angels and Insects (1995)'
 'Muppet Treasure Island (1996)' 'Braveheart (1995)' 'Taxi Driver (1976)'
 'Rumble in the Bronx (1995)' 'Birdcage, The (1996)'
 'Brothers McMullen, The (1995)' 'Bad Boys (1995)' 'Apollo 13 (1995)'
 'Batman Forever (1995)' 'Belle de jour (1967)']


In [5]:
print(data['item_feature_labels'][:30])

['Toy Story (1995)' 'GoldenEye (1995)' 'Four Rooms (1995)'
 'Get Shorty (1995)' 'Copycat (1995)'
 'Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)'
 'Twelve Monkeys (1995)' 'Babe (1995)' 'Dead Man Walking (1995)'
 'Richard III (1995)' 'Seven (Se7en) (1995)' 'Usual Suspects, The (1995)'
 'Mighty Aphrodite (1995)' 'Postino, Il (1994)'
 "Mr. Holland's Opus (1995)" 'French Twist (Gazon maudit) (1995)'
 'From Dusk Till Dawn (1996)' 'White Balloon, The (1995)'
 "Antonia's Line (1995)" 'Angels and Insects (1995)'
 'Muppet Treasure Island (1996)' 'Braveheart (1995)' 'Taxi Driver (1976)'
 'Rumble in the Bronx (1995)' 'Birdcage, The (1996)'
 'Brothers McMullen, The (1995)' 'Bad Boys (1995)' 'Apollo 13 (1995)'
 'Batman Forever (1995)' 'Belle de jour (1967)']


In [6]:
print(data['item_features'].toarray())

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [15]:
print(data['item_features'])

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
  (4, 4)	1.0
  (5, 5)	1.0
  (6, 6)	1.0
  (7, 7)	1.0
  (8, 8)	1.0
  (9, 9)	1.0
  (10, 10)	1.0
  (11, 11)	1.0
  (12, 12)	1.0
  (13, 13)	1.0
  (14, 14)	1.0
  (15, 15)	1.0
  (16, 16)	1.0
  (17, 17)	1.0
  (18, 18)	1.0
  (19, 19)	1.0
  (20, 20)	1.0
  (21, 21)	1.0
  (22, 22)	1.0
  (23, 23)	1.0
  (24, 24)	1.0
  :	:
  (1657, 1657)	1.0
  (1658, 1658)	1.0
  (1659, 1659)	1.0
  (1660, 1660)	1.0
  (1661, 1661)	1.0
  (1662, 1662)	1.0
  (1663, 1663)	1.0
  (1664, 1664)	1.0
  (1665, 1665)	1.0
  (1666, 1666)	1.0
  (1667, 1667)	1.0
  (1668, 1668)	1.0
  (1669, 1669)	1.0
  (1670, 1670)	1.0
  (1671, 1671)	1.0
  (1672, 1672)	1.0
  (1673, 1673)	1.0
  (1674, 1674)	1.0
  (1675, 1675)	1.0
  (1676, 1676)	1.0
  (1677, 1677)	1.0
  (1678, 1678)	1.0
  (1679, 1679)	1.0
  (1680, 1680)	1.0
  (1681, 1681)	1.0


In [7]:
print(data['train'].toarray())

[[5. 3. 4. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [5. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 5. 0. ... 0. 0. 0.]]


In [8]:
print(data['test'].toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [9]:
print(data['train'].toarray()[:1])

[[5. 3. 4. ... 0. 0. 0.]]


In [10]:
for i in data['train'].toarray()[:1][0]:
    print(i)

5.0
3.0
4.0
3.0
3.0
5.0
4.0
1.0
5.0
3.0
2.0
5.0
5.0
5.0
5.0
5.0
3.0
4.0
5.0
0.0
1.0
4.0
4.0
3.0
4.0
3.0
2.0
4.0
1.0
3.0
3.0
5.0
0.0
2.0
1.0
2.0
2.0
3.0
4.0
3.0
2.0
5.0
4.0
5.0
5.0
4.0
4.0
5.0
3.0
5.0
4.0
4.0
3.0
3.0
5.0
4.0
5.0
4.0
5.0
5.0
0.0
3.0
2.0
5.0
4.0
4.0
3.0
4.0
3.0
3.0
3.0
4.0
3.0
1.0
4.0
4.0
4.0
1.0
4.0
4.0
5.0
5.0
3.0
4.0
3.0
5.0
5.0
4.0
5.0
4.0
5.0
3.0
5.0
2.0
4.0
5.0
3.0
4.0
3.0
5.0
2.0
2.0
1.0
1.0
2.0
4.0
4.0
5.0
5.0
1.0
5.0
1.0
5.0
5.0
5.0
3.0
0.0
3.0
5.0
1.0
4.0
3.0
4.0
5.0
3.0
2.0
5.0
4.0
5.0
3.0
1.0
4.0
4.0
4.0
4.0
3.0
5.0
1.0
3.0
1.0
3.0
2.0
1.0
4.0
2.0
4.0
3.0
2.0
2.0
5.0
4.0
5.0
3.0
5.0
0.0
4.0
4.0
3.0
3.0
0.0
4.0
4.0
4.0
3.0
5.0
5.0
2.0
5.0
5.0
5.0
0.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
3.0
3.0
5.0
4.0
5.0
4.0
4.0
4.0
4.0
3.0
0.0
5.0
5.0
4.0
4.0
4.0
5.0
5.0
5.0
5.0
4.0
3.0
3.0
0.0
4.0
5.0
3.0
4.0
5.0
5.0
4.0
4.0
3.0
4.0
2.0
4.0
3.0
5.0
3.0
3.0
1.0
3.0
5.0
4.0
5.0
5.0
2.0
3.0
4.0
5.0
4.0
4.0
1.0
3.0
2.0
4.0
5.0
4.0
2.0
4.0
4.0
3.0
4.0
5.0
1.0
2.0
2.0
5.0
1.0
4.0
4.0
4.0


In [11]:
print(data['test'])

  (0, 19)	4
  (0, 32)	4
  (0, 60)	4
  (0, 116)	3
  (0, 154)	2
  (0, 159)	4
  (0, 170)	5
  (0, 188)	3
  (0, 201)	5
  (0, 264)	4
  (1, 12)	4
  (1, 49)	5
  (1, 250)	5
  (1, 279)	3
  (1, 280)	3
  (1, 289)	3
  (1, 291)	4
  (1, 296)	4
  (1, 311)	3
  (1, 313)	1
  (2, 244)	1
  (2, 293)	2
  (2, 322)	2
  (2, 327)	5
  (2, 330)	4
  :	:
  (940, 180)	5
  (940, 256)	4
  (940, 257)	4
  (940, 474)	4
  (940, 992)	4
  (941, 116)	4
  (941, 199)	4
  (941, 260)	4
  (941, 322)	3
  (941, 422)	5
  (941, 426)	5
  (941, 486)	4
  (941, 583)	4
  (941, 603)	4
  (941, 614)	3
  (942, 10)	4
  (942, 57)	4
  (942, 110)	4
  (942, 185)	5
  (942, 214)	5
  (942, 231)	4
  (942, 355)	4
  (942, 569)	1
  (942, 807)	4
  (942, 1066)	2


In [12]:
print(type(data['train']))

<class 'scipy.sparse.coo.coo_matrix'>


In [13]:
print(type(test_precision))

<class 'numpy.ndarray'>


In [14]:
test_precision

array([0.        , 0.        , 0.        , 0.33333334, 0.        ,
       0.        , 0.        , 0.        , 0.33333334, 0.        ,
       0.        , 0.        , 0.33333334, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.33333334, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.33333334, 0.        , 0.        ,
       0.33333334, 0.        , 0.        , 0.33333334, 0.        ,
       0.        , 0.        , 0.        , 0.6666667 , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.33333334,
       0.33333334, 0.        , 0.33333334, 0.        , 0.33333334,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.33333334, 0.        , 0.        ,
       0.        , 0.        , 0.33333334, 0.        , 0.        ,
       0.33333334, 0.6666667 , 0.33333334, 0.        , 0.33333334,
       0.        , 0.        , 0.        , 0.33333334, 0.33333